### ISSUE TITLE
How you got Token probablity 

### ISSUE THREAD

**Issue by owos** [pchizhov/picky_bpe#1]
I read the paper in your work but I didn't under the meaning of the term "token probability" as used in figure 3. Does this refer to the weights of the LM head (AKA output emebeddings) from a model?
if so, figure 3 will then be the  embedding weights of the LM head on the Y axis and the L2 norm of the input embeddings on the X axis, is this correct?

**Comment by pchizhov** [comment]
Hi @owos!
Token probability is simply 1 / token frequency in the training corpus. It was meant to show how often the model was exposed to each token during training.

**Comment by owos** [comment]
ohkay, thank you for your response, I later saw that in your paper. What I got curious about now is why you used the input embedding layer instead of the output layer like Lander et al.  used in their paper.
